FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv

# Create and activate virtual environment
RUN python3 -m venv /venv
RUN /venv/bin/pip install websockets

# Copy source code
COPY /src /app

# Set working directory
WORKDIR /app
VOLUME /app

# Expose port
EXPOSE 8765

# Run the application
CMD ["/venv/bin/python", "server.py"]