apiVersion: v1
kind: Service
metadata:
  name: chatrequestserver-service
spec:
  selector:
    app: chatrequestserver  # Updated to match the labels in deployment.yaml
  ports:
    - protocol: TCP
      port: 8765  # External port
      targetPort: 8765  # Matches the containerPort in deployment
  type: LoadBalancer  # Change to NodePort if no cloud provider is used
