FROM nginx:latest

# Set the working directory
WORKDIR /usr/share/nginx/html

# Copy the static files to the Nginx HTML directory
COPY /src /usr/share/nginx/html

# Create the custom Nginx configuration file
RUN echo 'worker_processes 1;' > /etc/nginx/nginx.conf && \
    echo 'events { worker_connections 1024; }' >> /etc/nginx/nginx.conf && \
    echo 'http { include mime.types; default_type application/octet-stream; sendfile on; keepalive_timeout 65;' >> /etc/nginx/nginx.conf && \
    echo 'server { listen 80; location / { root /usr/share/nginx/html; index index.html index.htm; }' >> /etc/nginx/nginx.conf && \
    echo 'location /ws/ { proxy_pass http://websocket_server:8765; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "Upgrade"; proxy_set_header Host $host; proxy_cache_bypass $http_upgrade; } } }' >> /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Run Nginx
CMD ["nginx", "-g", "daemon off;"]
